#This script has been generated by Peach Generator 1.
#Rerunning Peach Generator on this script will lead to a loss of your added python code.

def start(c, input_1, input_2):
    return [[input_1, input_2]]
