#This script has been generated by Peach Generator 1.
#Rerunning Peach Generator on this script will lead to a loss of your added python code.

def start(c, plan_in, ct_in, grid_size):
    import ServiceUtility
    import os
    import time
    import shutil
    unique_relative_output_dir = "output_" + str(time.time()).replace(".", "")
    dir_path = os.path.dirname(os.path.realpath(__file__))
    unique_output_dir = os.path.join(dir_path, unique_relative_output_dir)
    os.makedirs(unique_output_dir)

    #your output ports as output files

    dose_out_filename = "dose_out.???"
    dose_out = os.path.join(unique_output_dir, dose_out_filename)
    with open(dose_out, "w") as dose_out_f:
        dose_out_f.write("This is the output of port \"dose_out\"")

    print "Running DoseCalc"
    availableFiles = ServiceUtility.make_available(c, [[dose_out, dose_out_filename]])
    shutil.rmtree(unique_output_dir)
    return availableFiles
